### ISSUE TITLE
configure the nextjs middleware

### ISSUE THREAD

**Issue by gouravg8** [gouravg8/twt-ai#9]
**Is your feature request related to a problem? Please describe.**
protect the routes from new user and logged in user should not access auth routes

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
![image](https://github.com/user-attachments/assets/f6d7fc7e-da59-43bd-a956-fc8ac255291c)

**Additional context**
-

**Comment by Percobain** [comment]
Hey, can I work on this?
